- name: Build new Image
  hosts: all
  become: true
  vars:
    openscap_upload: true
    openscap_remediate: false

  tasks:
  - name: compose new image
    command: composer-cli compose start azure-rhel8-golden-image vhd
    register: command_result

  - name: display the command output
    debug:
      var: command_result

  - name: set uuid var
    set_fact:
      uuid: "{{ command_result.stdout.split()[1] }}"

  - name: display the uuid var
    debug:
      var: uuid

  - name: wait on image build to complete
    command: composer-cli compose info {{ uuid }} | head -1
    #command: /tmp/test
    register: build
    until: build.stdout.find("FINISHED") != -1
    retries: 200
    delay: 5
