- name: Setup Django, Nginx, Gunicorn, and PostgreSQL to serve an application
  hosts: all
  become: true
  vars:
    db_name: rhdemo
    db_user: rhdemo
    db_pass: rhdemo123
    db_host: 127.0.0.1
    release: master
  tasks:
  - include_role:
      name: ansible-role-postgresql
    vars:
      postgresql_db_name: "{{ db_name }}"
      postgresql_db_user: "{{ db_user }}"
      postgresql_db_pass: "{{ db_pass }}"

  - include_role:
      name: ansible-role-rh-demo-web-app
    vars:
      rh_demo_web_app_release: "{{ release }}"
      rh_demo_web_app_db: "{{ db_name }}"
      rh_demo_web_app_db_host: "{{ db_host }}"
      rh_demo_web_app_db_user: "{{ db_user }}"
      rh_demo_web_app_db_pass: "{{ db_pass }}"
