- name: Setup Django, Nginx, Gunicorn, and PostgreSQL to serve an application
  hosts: all
  vars:
    appuser: djangotest
    appgroup: djangotest
    application: djangotest
    db_name: django
    db_user: django
    db_pass: django123

  tasks:
  - name: Install Python36, python virtualenv and python3-psycopg2
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python36
      - python3-virtualenv
      - python3-psycopg2

  - name: Add the system group for the application
    group:
      name: "{{ appgroup }}"
      state: present

  - name: Add the system user for the application
    user:
      name: "{{ appuser }}"
      group: "{{ appgroup }}"

  - name: Create a directory if it does not exist
    file:
      path: "/srv/{{ appuser }}"
      state: directory
      mode: '0755'
      owner: "{{ appuser }}"
      group: "{{ appgroup }}"

  - name: Install django, gunicorn, and psycopg2
    pip:
      name: django, gunicorn
      virtualenv: "/srv/{{ appuser }}/venv"
    become: yes
    become_user: "{{ appuser }}"

  - name: Install PostgreSQL
    package:
      name: postgresql-server
      state: present

  - name: init PostgreSQL DB
    command: /usr/bin/postgresql-setup --initdb
    args:
      creates: /var/lib/pgsql/data/postgresql.conf

  - name: Start service postgresql, if not started
    service:
      name: postgresql
      state: started

  - name: Create a new database with name "acme"
    postgresql_db:
      name: "{{ db_name }}"
      
