- name: Setup Django, Nginx, Gunicorn, and PostgreSQL to serve an application
  hosts: all
  become: true
  vars:

  tasks:
  - name: Get DB hosts
    set_fact:
      rh_demo_web_app_db_host: "{{ db_public_ip }}"

  - include_role:
      name: ansible-role-rh-demo-web-app
