- name: install jenkins
  hosts: all
  become: true
  vars:
    my_jenkins_params:
      url_username: admin
      url_password: admin


  tasks:
  - name: Install plugin
    jenkins_plugin:
      name: ansible-tower
      version: "0.9.2"
      url_username: admin
      url_password: admin
