- name: install jenkins
  hosts: all
  become: true
  vars:


  tasks:
  - name: Install plugin
    jenkins_plugin:
      name: ansible-tower
      version: "0.9.2"
      url: "http://localhost:8080"
