- name: install jenkins
  hosts: all
  become: true
  vars:
    my_jenkins_params:
      url_username: admin
      url_password: admin


  tasks:
  - name: Install plugin
    jenkins_plugin:
      name: ansible-tower
      version: "0.9.2"
      url_username: admin
      url_password: admin

  - name: Install plugin
    jenkins_plugin:
      name: credentials
      version: "1.22"
      url_username: admin
      url_password: admin

  - name: Install plugin
    jenkins_plugin:
      name: script-security
      version: "1.17"
      url_username: admin
      url_password: admin
