---
- name: Create user
  hosts: all
  vars:
    user_name:

  tasks:
  - name: Create user
    win_user:
      name: "{{ user_name }}"
      password: "{{ user_password }}"
      state: present
      groups:
        - Users
